configurations.all {
	resolutionStrategy {
		force group: "com.liferay.portal", name: "com.liferay.portal.test", version: "7.1.0"
	}
}

dependencies {
	testIntegrationImplementation group: "com.liferay.portal", name: "release.portal.api"
	testIntegrationImplementation project(":modules:employee-rest:employee-rest-api")
	testIntegrationImplementation project(":modules:employee-rest:employee-rest-client")
}