info:
    description: "EmployeeRest REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "EmployeeRest"
    version: v1.0

openapi: 3.0.1

paths:
    /employees:
        get:
            operationId: getEmployeesPage
            responses:
                '200':
                    description: List of Employees
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Employee'
                        application/xml:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Employee'

        post:
            operationId: postEmployee
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Employee'
                    application/xml:
                        schema:
                            $ref: '#/components/schemas/Employee'
            responses:
                '200':
                    description: Created Employee
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Employee'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/Employee'

    /employees/{employeeId}:
        get:
            operationId: getEmployee
            parameters:
                - name: employeeId
                  in: path
                  required: true
                  schema:
                      type: integer
            responses:
                '200':
                    description: Employee Details
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Employee'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/Employee'

        put:
            operationId: putEmployee
            parameters:
                - name: employeeId
                  in: path
                  required: true
                  schema:
                      type: integer
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Employee'
                    application/xml:
                        schema:
                            $ref: '#/components/schemas/Employee'
            responses:
                '200':
                    description: Updated Employee
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Employee'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/Employee'

        delete:
            operationId: deleteEmployee
            parameters:
                - name: employeeId
                  in: path
                  required: true
                  schema:
                      type: integer
            responses:
                '204':
                    description: Deleted
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Employee'
                        application/xml:
                            schema:
                                $ref: '#/components/schemas/Employee'

components:
    schemas:
        Employee:
            type: object
            properties:
                employeeId:
                    type: integer
                firstName:
                    type: string
                lastName:
                    type: string
                emailAddress:
                    type: string
                phoneNumber:
                    type: string
                addressLine1:
                    type: string
                addressLine2:
                    type: string
                city:
                    type: string
                zipCode:
                    type: string
                designation:
                    type: string